name: Build android app

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build for Android
        run: make

  upload:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Upload to Deploygate
        run: |
          curl \
            --url "https://deploygate.com/api/users/${{ secrets.DEPLOYGATE_USER }}/apps" \
            -H "Authorization: Bearer ${{ secrets.DEPLOYGATE_API_KEY }}" \
            -X POST \
            -F "file=@daiso_barcode_scanner/build/app/outputs/bundle/release/app-release.aab" \
            --form-string "distribution_name=develop" \
            --form-string "release_note=Build from Github actions" \
            --form-string "message=git: ${{ github.sha }}"
